# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SVN-Agent
version:      0.03
version_from: lib/SVN/Agent.pm
installdirs:  site
requires:
    Class::Accessor:               
    File::Slurp:                   
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
